### ISSUE TITLE
Erro de semântica 

### ISSUE THREAD

**Issue by PauloTrynado** [carlosdelfino/carlosdelfino.github.com#10]
Não estou entendendo a quinta linha, falta informação nela.

**Comment by carlosdelfino** [comment]
Ok, estou verificando, você quis dizer quinto paragrafo não?

**Comment by carlosdelfino** [comment]
Algumas revisões no commit a92618ec7a34ab34d83ded9aec659c8257c1a850

**Comment by PauloTrynado** [comment]
http://carlosdelfino.eti.br/workshop/estacio_ceara/2016_2/Instalando_ambiente_para_workshop_estacioce_qemu_eclipse_arm/

quinta linha, logo abaixo dos comandos: pacman / pacman -Suy / pacman -Suy

**Comment by PauloTrynado** [comment]
Possível erro de sentido na quarta linha depois dos comandos.
