### ISSUE TITLE
Erro de semântica

### ISSUE THREAD

**Issue by PauloTrynado** [carlosdelfino/carlosdelfino.github.com#12]
http://carlosdelfino.eti.br/workshop/estacio_ceara/2016_2/Instalando_ambiente_para_workshop_estacioce_qemu_eclipse_arm/

quinta linha, logo abaixo dos comandos: pacman / pacman -Suy / pacman -Suy

**Comment by PauloTrynado** [comment]
Possível erro de sentido na quarta linha depois dos comandos.

**Comment by carlosdelfino** [comment]
Este issue é repetido veja o issue de #10, favor corrigir o anterior pois ele já é referenciado no commit que corrige o texto.

**Comment by PauloTrynado** [comment]
Não estou entendendo a quinta linha, falta informação nela.
